### ISSUE TITLE
how do i run this on windows?

### ISSUE THREAD

**Issue by NovaAshwolfDev** [LegendL3n/RustyController#66]
how do i run this on windows i need this because im also figuring out the packet structure but i need to double check in wireshark but none of the utility's i found work on windows but this one does from what i have seen in the documentation

**Comment by davidgomesdev** [comment]
Just saw this issue now, you should be able to run it as you would any Rust project, by running `cargo run` in a terminal as administrator.

**Comment by davidgomesdev** [comment]
Anyway, you can see the packet structure in the `ps_move` module.

For instance, the packet for setting led and rumble is [here](https://github.com/davidgomesdev/RustyController/blob/main/server/src/ps_move/controller.rs#L303).
